{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: google-api-python-client in /opt/conda/miniconda3/lib/python3.10/site-packages (2.126.0)\n",
      "Collecting google-api-python-client\n",
      "  Downloading google_api_python_client-2.127.0-py2.py3-none-any.whl.metadata (6.7 kB)\n",
      "Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-python-client) (0.20.4)\n",
      "Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-python-client) (2.28.2)\n",
      "Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-python-client) (0.2.0)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-python-client) (2.18.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-python-client) (4.1.1)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.63.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (4.21.12)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.23.0)\n",
      "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.28.2)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (5.3.3)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (4.9)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client) (3.1.2)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /opt/conda/miniconda3/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.5.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.6)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.26.18)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2024.2.2)\n",
      "Downloading google_api_python_client-2.127.0-py2.py3-none-any.whl (12.7 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m12.7/12.7 MB\u001b[0m \u001b[31m92.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: google-api-python-client\n",
      "  Attempting uninstall: google-api-python-client\n",
      "    Found existing installation: google-api-python-client 2.126.0\n",
      "    Uninstalling google-api-python-client-2.126.0:\n",
      "      Successfully uninstalled google-api-python-client-2.126.0\n",
      "Successfully installed google-api-python-client-2.127.0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: google-cloud-speech in /opt/conda/miniconda3/lib/python3.10/site-packages (2.26.0)\n",
      "Requirement already satisfied: google-cloud-bigtable in /opt/conda/miniconda3/lib/python3.10/site-packages (2.23.1)\n",
      "Requirement already satisfied: google-cloud-core in /opt/conda/miniconda3/lib/python3.10/site-packages (2.4.1)\n",
      "Requirement already satisfied: google-api-core in /opt/conda/miniconda3/lib/python3.10/site-packages (2.18.0)\n",
      "Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-cloud-speech) (2.28.2)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-cloud-speech) (1.23.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-cloud-speech) (4.21.12)\n",
      "Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-cloud-bigtable) (0.13.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core) (1.63.0)\n",
      "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core) (2.28.2)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-speech) (1.62.1)\n",
      "Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-speech) (1.62.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-speech) (5.3.3)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-speech) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/miniconda3/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-speech) (4.9)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core) (3.6)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core) (1.26.18)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core) (2024.2.2)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /opt/conda/miniconda3/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-speech) (0.5.1)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: moviepy in /opt/conda/miniconda3/lib/python3.10/site-packages (1.0.3)\n",
      "Requirement already satisfied: decorator<5.0,>=4.0.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from moviepy) (4.4.2)\n",
      "Requirement already satisfied: tqdm<5.0,>=4.11.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from moviepy) (4.66.2)\n",
      "Requirement already satisfied: requests<3.0,>=2.8.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from moviepy) (2.28.2)\n",
      "Requirement already satisfied: proglog<=1.0.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from moviepy) (0.1.10)\n",
      "Requirement already satisfied: numpy>=1.17.3 in /opt/conda/miniconda3/lib/python3.10/site-packages (from moviepy) (1.22.4)\n",
      "Requirement already satisfied: imageio<3.0,>=2.5 in /opt/conda/miniconda3/lib/python3.10/site-packages (from moviepy) (2.34.0)\n",
      "Requirement already satisfied: imageio-ffmpeg>=0.2.0 in /opt/conda/miniconda3/lib/python3.10/site-packages (from moviepy) (0.4.9)\n",
      "Requirement already satisfied: pillow>=8.3.2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from imageio<3.0,>=2.5->moviepy) (9.2.0)\n",
      "Requirement already satisfied: setuptools in /opt/conda/miniconda3/lib/python3.10/site-packages (from imageio-ffmpeg>=0.2.0->moviepy) (69.2.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (3.6)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (1.26.18)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/miniconda3/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (2024.2.2)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: pytube in /opt/conda/miniconda3/lib/python3.10/site-packages (15.0.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "Reading package lists... Done\n",
      "Building dependency tree       \n",
      "Reading state information... Done\n",
      "Some packages could not be installed. This may mean that you have\n",
      "requested an impossible situation or if you are using the unstable\n",
      "distribution that some required packages have not yet been created\n",
      "or been moved out of Incoming.\n",
      "The following information may help to resolve the situation:\n",
      "\n",
      "The following packages have unmet dependencies:\n",
      " ffmpeg : Depends: libavcodec58 (= 7:4.2.7-0ubuntu0.1)\n",
      "          Depends: libavdevice58 (= 7:4.2.7-0ubuntu0.1) but it is not going to be installed\n",
      "          Depends: libavfilter7 (= 7:4.2.7-0ubuntu0.1)\n",
      "          Depends: libavformat58 (= 7:4.2.7-0ubuntu0.1) but it is not going to be installed\n",
      "          Depends: libavresample4 (= 7:4.2.7-0ubuntu0.1) but it is not going to be installed\n",
      "          Depends: libavutil56 (= 7:4.2.7-0ubuntu0.1) but it is not going to be installed\n",
      "          Depends: libpostproc55 (= 7:4.2.7-0ubuntu0.1) but it is not going to be installed\n",
      "          Depends: libsdl2-2.0-0 (>= 2.0.10) but it is not installable\n",
      "          Depends: libswresample3 (= 7:4.2.7-0ubuntu0.1) but it is not going to be installed\n",
      "          Depends: libswscale5 (= 7:4.2.7-0ubuntu0.1) but it is not going to be installed\n",
      "E: Unable to correct problems, you have held broken packages.\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade google-api-python-client\n",
    "!pip install --upgrade google-cloud-speech google-cloud-bigtable google-cloud-core google-api-core\n",
    "!pip install moviepy\n",
    "!pip install pytube\n",
    "!sudo apt-get install ffmpeg -y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import subprocess\n",
    "from pytube import YouTube\n",
    "from google.cloud import speech_v1 as speech\n",
    "from google.cloud import storage\n",
    "import pandas as pd\n",
    "\n",
    "#define all functions, also make sure that if we encounter a problem we know exactly which step is wrong\n",
    "#download the audio from a given YouTube URL using pytube\n",
    "def download_audio(url):\n",
    "    try:\n",
    "        yt = YouTube(url)\n",
    "        audio_stream = yt.streams.filter(only_audio=True).order_by('abr').desc().first()\n",
    "        filename = audio_stream.download()\n",
    "        return filename\n",
    "    except Exception as e:\n",
    "        print(f\"Failed to download audio from {url}. Reason: {e}\")\n",
    "        return None\n",
    "\n",
    "#adjust audio to same format which can be used for speech-to-text api (adjust sample rate, channels and output path)\n",
    "def adjust_audio(input_audio_path, output_audio_path, target_sample_rate=16000, channels=1):\n",
    "    if not output_audio_path.endswith('.wav'):\n",
    "        output_audio_path = os.path.splitext(output_audio_path)[0] + '.wav'\n",
    "    \n",
    "    command = [\n",
    "        \"ffmpeg\", #use ffmpeg\n",
    "        \"-i\", input_audio_path,          \n",
    "        \"-ar\", str(target_sample_rate),   \n",
    "        \"-ac\", str(channels),           \n",
    "        \"-y\",                            \n",
    "        output_audio_path                 \n",
    "    ]\n",
    "    try:\n",
    "        subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n",
    "        return output_audio_path\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        print(f\"Failed to adjust audio properties: {e.stderr.decode()}\")\n",
    "\n",
    "\n",
    "# upload file to google cloud storage\n",
    "def upload_to_gcs(local_file_path, bucket_name, gcs_file_path):\n",
    "    try:\n",
    "        subprocess.run(\n",
    "            [\"gsutil\", \"cp\", local_file_path, f\"gs://{bucket_name}/{gcs_file_path}\"],\n",
    "            check=True,\n",
    "            capture_output=True\n",
    "        )\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        print(f\"Failed to upload {local_file_path} to GCS: {e.stderr.decode()}\")\n",
    "\n",
    "#using speech-to-text api to get the transcript results\n",
    "def transcribe_audio_gcs(gcs_uri):\n",
    "    client = speech.SpeechClient()\n",
    "    audio = speech.RecognitionAudio(uri=gcs_uri)\n",
    "    config = speech.RecognitionConfig(\n",
    "        encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,\n",
    "        sample_rate_hertz=16000,\n",
    "        language_code=\"en-US\",#get english transcript\n",
    "    )\n",
    "    operation = client.long_running_recognize(config=config, audio=audio)\n",
    "    response = operation.result(timeout=1000)#set timeout\n",
    "    #combine text from all the transcripts\n",
    "    transcripts = ' '.join([result.alternatives[0].transcript for result in response.results])\n",
    "    return transcripts\n",
    "\n",
    "# upload text content to a google cloud storage\n",
    "def upload_text_to_gcs(bucket_name, blob_name, content):\n",
    "    storage_client = storage.Client()\n",
    "    bucket = storage_client.bucket(bucket_name)\n",
    "    blob = bucket.blob(blob_name)\n",
    "    blob.upload_from_string(content)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "#usage for multiple videos\n",
    "\n",
    "#to process audio using defined functions\n",
    "def process_audio(url, bucket_name):\n",
    "    audio_path = download_audio(url) #download audio\n",
    "    text = ''  #initialise variable\n",
    "    if audio_path:\n",
    "        #adjust audio name\n",
    "        base_name = os.path.basename(audio_path)\n",
    "        video_id = os.path.splitext(base_name)[0]\n",
    "        adjusted_audio_path = f'{video_id}_adjusted.wav'\n",
    "        #adjust audio\n",
    "        adjust_audio(audio_path, adjusted_audio_path, 16000, 1)\n",
    "        gcs_audio_filename = f'{video_id}.wav'\n",
    "        #upload audio to gcs\n",
    "        upload_to_gcs(adjusted_audio_path, bucket_name, gcs_audio_filename)\n",
    "        gcs_uri = f'gs://{bucket_name}/{gcs_audio_filename}'\n",
    "        #get text and upload to gcs\n",
    "        text = transcribe_audio_gcs(gcs_uri)  \n",
    "        text_blob_name = gcs_audio_filename.replace('.wav', '.txt')\n",
    "        upload_text_to_gcs(bucket_name, text_blob_name, text)\n",
    "    return text  \n",
    "\n",
    "#to handle each url in the dataframe\n",
    "def process_audio_for_dataframe(url, bucket_name):\n",
    "    try:\n",
    "        return process_audio(url, bucket_name)\n",
    "    except Exception as e:\n",
    "        print(f\"Error processing {url}: {e}\")\n",
    "        return \"\"\n",
    "    \n",
    "if __name__ == '__main__':\n",
    "    #set project id and bucket name\n",
    "    PROJECT_ID = 'st446-project'\n",
    "    BUCKET_NAME = 'st446-project' \n",
    "    # get the csv file containing urls from previous part(URLs Extracting.ipynb)\n",
    "    df = pd.read_csv('gs://st446-project/urls_combined.csv')\n",
    "    \n",
    "    #apply the audio processing function to each url, also save the results in a new column in the csv file\n",
    "    df['text'] = df['URL'].apply(lambda url: process_audio_for_dataframe(url, BUCKET_NAME))\n",
    "\n",
    "    #save the final dataframe containing transcripts\n",
    "    df.to_csv(f'gs://{BUCKET_NAME}/urls_with_transcripts.csv', index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
